### ISSUE TITLE
Configuração Laravel

### ISSUE THREAD

**Issue by yurimachados** [yurimachados/laravel_ecommerce#3]
### Objetivo
Configurar o ambiente de desenvolvimento e inicializar o projeto Laravel.

### Subtasks

- [x] 1. Instalar o Composer, se necessário.
- [x] 2. Criar um novo projeto Laravel utilizando o Composer.
- [x] 3. Definir o nome do projeto, fuso horário e chave de criptografia no arquivo .env.
- [x] 4. Configurar o arquivo .env com as credenciais do banco de dados.
- [x] 5. Criar e migrar as tabelas de banco de dados padrão do Laravel, como usuários e migrações.
- [x] 6. Inicializar um repositório Git para controle de versão do projeto.
