### ISSUE TITLE
Configuração Vue.js

### ISSUE THREAD

**Issue by yurimachados** [yurimachados/laravel_ecommerce#4]
### Objetivo

Configurar o ambiente de desenvolvimento e integrar Vue.js ao projeto Laravel.

### Subtasks

- [x] 1. Instalar o Node.js, se necessário.
- [x] 2. Configurar o ambiente de desenvolvimento com Vue.js.
- [x] 3. Criar os componentes básicos do front-end usando Vue.js (ex: cabeçalho, rodapé).
- [x] 4. Integrar os componentes Vue.js às views do projeto Laravel.
